#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Creates a personalized open source philosophy statement
# Author: [Your Name]

clear

echo "=========================================="
echo "   OPEN SOURCE MANIFESTO GENERATOR        "
echo "=========================================="
echo ""
echo "This tool will help you create your personal"
echo "open source philosophy statement."
echo ""
echo "Based on the principles of the Apache HTTP Server"
echo "and the broader open source movement."
echo ""

# Get user input with validation
while true; do
    read -p "1. Name one open-source tool you use every day: " TOOL
    if [ -n "$TOOL" ]; then
        break
    else
        echo "   Please enter a tool name."
    fi
done

while true; do
    read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
    if [ -n "$FREEDOM" ]; then
        break
    else
        echo "   Please enter one word."
    fi
done

while true; do
    read -p "3. Name one thing you would build and share freely: " BUILD
    if [ -n "$BUILD" ]; then
        break
    else
        echo "   Please enter something you'd build."
    fi
done

# Get current information
DATE=$(date "+%B %d, %Y")
USERNAME=$(whoami)
HOSTNAME=$(hostname)
OUTPUT_FILE="manifesto_${USERNAME}_$(date +%Y%m%d_%H%M%S).txt"

echo ""
echo "Generating your manifesto..."
sleep 1

# Create the manifesto content
cat > "$OUTPUT_FILE" << EOF
========================================
     OPEN SOURCE MANIFESTO
========================================

Generated: $DATE
Author: $USERNAME
System: $HOSTNAME

========================================
MY OPEN SOURCE PHILOSOPHY
========================================

I, $USERNAME, believe in the power of open source software.

Every day, I use $TOOL — a tool that exists because someone,
somewhere, chose to share their work freely with the world.
This is not merely convenient; it represents a fundamental
belief that knowledge and tools should be accessible to all.

To me, freedom means $FREEDOM. In the context of software,
this means:

• The freedom to use software for any purpose
• The freedom to study how it works and learn from it
• The freedom to modify it to suit my needs
• The freedom to share improvements with others

The Apache HTTP Server taught us that open source isn't just
about free code — it's about community governance, transparent
development, and the belief that better software emerges when
we build together. For 25 years, Apache has powered the web,
proving that a community of volunteers can create something
that rivals and surpasses corporate alternatives.

I commit to building $BUILD and sharing it openly. Because
innovation doesn't happen in isolation — it happens when we
stand on the shoulders of giants, improve what came before,
and pass those improvements forward.

"Standing on the shoulders of giants" is not just a metaphor.
In open source, it is the literal reality of every line of
code I will ever write. The giants are the developers who
chose to share under licenses like the Apache License 2.0,
the GPL, and the MIT License — licenses that protect freedom
while enabling collaboration.

Open source ensures those shoulders belong to everyone.

This is my manifesto. I choose to build in the open.

========================================
"Inspired by the GNU Manifesto,
the Apache Way, and the spirit of
collaborative creation."
========================================

Generated by: Open Source Manifesto Generator v1.0
EOF

echo ""
echo "=========================================="
echo -e "\033[32m✓ Manifesto saved to: $OUTPUT_FILE\033[0m"
echo "=========================================="
echo ""
echo "PREVIEW:"
echo "=========================================="
head -30 "$OUTPUT_FILE"
echo "..."
echo "=========================================="
echo ""
echo "Full manifesto is available in: $OUTPUT_FILE"
echo ""
echo "You can view it with: cat $OUTPUT_FILE"
